异常处理

```python
import math
for i in range(10):
    try:
        number=input('请输入一个数')
        if number == '+':
            break
        result=1/math.log(float(number))
        print(result)
    except ValueError:
        print('input>0')
    except ZeroDivisionError:
        print('分母不等于0')
   ## 此时当输入一个小于0的数此时不会报错 而是返回一个提示
try:
    print('123')
finally:
    print('finally')
## 执行完毕执行finally，当出现异常时会跳过错误进行执行finally
```

